# Generated by Django 5.2.7 on 2025-10-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitycampus',
            old_name='campus_id',
            new_name='campus_ID',
        ),
    ]
